-- Creation de nouveaux types

CREATE TYPE adresse_type AS OBJECT (
    numero_rue NUMBER,
    nom_rue VARCHAR2(100),
    nom_ville VARCHAR2(100)
);

CREATE TYPE departement_type AS OBJECT (
    numDept NUMBER,
    nomDept VARCHAR2(20),
    lieu VARCHAR2(50)
);

CREATE TYPE employe_type AS OBJECT (
    matricule NUMBER,
    nom VARCHAR2(50),
    adresse adresse_type,
    salaire NUMBER,
    superieur NUMBER,
    departement REF departement_type
);

CREATE TABLE departement (
  departement_data departement_type
) NESTED TABLE OF departement_type;

CREATE TABLE employe (
  employe_data employe_type
) NESTED TABLE OF employe_type;

SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TYPE';


-- Ajouter des données dans les nouvelles tables

1-
INSERT INTO departement (numDept, nomDept, lieu) 
    VALUES (10, 'dep10', 'ville1');
INSERT INTO departement (numDept, nomDept, lieu) 
    VALUES (20, 'Dep20', 'ville2');

INSERT INTO employe (matricule, nom, adresse, 
    salaire, superieur, departement)
VALUES (1, 'emp1', adresse_type(123, 'cite1',
    'ville1'), 3000, NULL, (SELECT REF(d) FROM 
    departement d WHERE d.numDept = 10));

INSERT INTO employe (matricule, nom, adresse,
    salaire, superieur, departement)
    VALUES (2, 'emp2', adresse_type(456,
    'cite2', 'ville2'), 3500, 1, (SELECT REF(d)
    FROM departement d WHERE d.numDept = 10));

INSERT INTO employe (matricule, nom, adresse,
    salaire, superieur, departement)
    VALUES (3, 'emp3', adresse_type(789, 
    'cite3', 'ville1'), 3200, 1, (SELECT REF(d) 
    FROM departement d WHERE d.numDept = 20));

2-
SELECT e.matricule, e.adresse.nom_ville AS 
    ville_habitation, (SELECT e2.nom FROM employe e2 
    WHERE e2.matricule = e.superieur) AS nom_superieur,
    d.nomDept AS departement_travail FROM employe e
JOIN departement d ON e.departement = d.numDept;


3-
SELECT e.nom FROM employe e JOIN departement d 
    ON e.departement = d.numDept WHERE d.numDept = 10;




-- Modification des données 
1-
UPDATE employe SET departement = (SELECT REF(d) 
    FROM departement d WHERE d.numDept = 20)
    WHERE matricule = 3;

2-
UPDATE employe SET superieur = 2,departement = 
    (SELECT REF(d) FROM departement d WHERE 
    d.numDept = 10)WHERE matricule = 3;







-- Exemple sur le type Array 
1-
CREATE TYPE personne_type AS OBJECT (
    nom VARCHAR2(50),
    prenoms VARCHAR2(200) ARRAY[4],
    telephones VARCHAR2(200) ARRAY[4]
);

CREATE TABLE personne (
    id NUMBER GENERATED BY DEFAULT ON NULL AS 
    IDENTITY PRIMARY KEY,
    personne personne_type
);

2-
CREATE TYPE personne_type AS OBJECT (
    nom VARCHAR2(50),
    prenoms VARCHAR2(200) ARRAY[4],
    telephones VARCHAR2(200) ARRAY[4]
);

CREATE TABLE personne (
    id NUMBER GENERATED BY DEFAULT ON NULL 
    AS IDENTITY PRIMARY KEY,
    personne personne_type
);

3-
UPDATE personne SET personne.prenoms[1] = 'Lyes'
    WHERE id = 1;

4-
UPDATE personne SET personne.prenoms = personne.prenoms || 'Ali'
    WHERE id = 1;

5-
SELECT personne.nom, personne.prenoms, personne.telephones
    FROM personne;
